apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-pods
spec:
  version: v0.1.0
  homepage: https://github.com/noahfan/kubectl-node-pods
  shortDescription: "Show node pod and resource balance"
  description: |
    A kubectl plugin that displays pod counts and CPU/Memory
    request pressure across nodes to identify scheduling imbalance.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://example.com/kubectl-node_pods-darwin-arm64.tar.gz
    sha256: "fadfd6bbc68fd8ab988b683f8f17874ccd289dfd1edbc6b7436912bcd5e9c9e9"
    bin: kubectl-node_pods
